---
vm_name: rails_project
path: /var/www/rails_project
packages:
  - curl
  - libcurl3
  - libcurl3-gnutls
  - libcurl4-openssl-dev
  - imagemagick
environment_file: /ansible_teste/.envrc


app_name: '{{ vm_name }}'
rails_user: rails
group_name: '{{ rails_user }}'

user_home_path: '/home/{{ rails_user }}'

app_path: "{{ path }}/current"
app_public_path: "{{ app_path }}/public"
app_config_path: "{{ app_path }}/config"
app_temp_path: "/tmp{{ app_path }}"
app_logs_path: "{{ app_path }}/log"

releases_path: '{{ path }}/releases'
shared_path: '{{ path }}/shared'

unicorn_sock_path: "/tmp/unicorn.sock"

use_apt_proxy: false
