require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DocumentsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Document. As you add validations to Document, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      file_file_name: "O livro de Ruby"
    }
  }



  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DocumentsController. Be sure to keep this updated too.


  describe "GET #index" do
    login_coach
    it "assigns all documents as @documents" do
      document = Document.create! valid_attributes
      get :index, {}
      expect(assigns(:documents)).to eq([document])
    end
  end

  describe "GET #show" do
    login_coach
    it "assigns the requested document as @document" do
      document = Document.create! valid_attributes
      get :show, {:id => document.to_param}
      expect(assigns(:document)).to eq(document)
    end
  end

  describe "GET #new" do
    login_coach
    it "assigns a new document as @document" do
      get :new, {}
      expect(assigns(:document)).to be_a_new(Document)
    end
  end

  describe "GET #edit" do
    login_coach
    it "assigns the requested document as @document" do
      document = Document.create! valid_attributes
      get :edit, {:id => document.to_param}
      expect(assigns(:document)).to eq(document)
    end
  end

  describe "POST #create" do
    login_coach
    context "with valid params" do
      it "creates a new Document" do
        expect {
          post :create, {:document => valid_attributes}
        }.to change(Document, :count).by(1)
      end

      it "assigns a newly created document as @document" do
        post :create, {:document => valid_attributes}
        expect(assigns(:document)).to be_a(Document)
        expect(assigns(:document)).to be_persisted
      end

      it "redirects to the created documents list" do
        post :create, {:document => valid_attributes}
        expect(response).to redirect_to(documents_path)
      end
    end
  end

  describe "PUT #update" do
    login_coach
    context "with valid params" do
      let(:new_attributes){
        {
          file_file_name: "O livro de Rails"
        }
      }

      it "updates the requested document" do
        document = Document.create! valid_attributes
        put :update, {:id => document.to_param, :document => new_attributes}

        document.reload
        expect(document.file_file_name).to eq(new_attributes[:file_file_name])
      end

      it "assigns the requested document as @document" do
        document = Document.create! valid_attributes
        put :update, {:id => document.to_param, :document => valid_attributes}
        expect(assigns(:document)).to eq(document)
      end

      it "redirects to the documents list" do
        document = Document.create! valid_attributes
        put :update, {:id => document.to_param, :document => valid_attributes}
        expect(response).to redirect_to(documents_path)
      end
    end
  end

  describe "DELETE #destroy" do
    login_coach
    it "destroys the requested document" do
      document = Document.create! valid_attributes
      expect {
        delete :destroy, {:id => document.to_param}
      }.to change(Document, :count).by(-1)
    end

    it "redirects to the documents list" do
      document = Document.create! valid_attributes
      delete :destroy, {:id => document.to_param}
      expect(response).to redirect_to(documents_url)
    end
  end

end
