require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ExamsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Exam. As you add validations to Exam, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      player_id: 1,
      height: Faker::Number.between(158, 190),
      weight: Faker::Number.between(50, 105),
      exam_date: Faker::Date.backward(14)
    }
  }

  let(:invalid_attributes) {
    {
      player_id: 1,
      height: nil,
      weight: Faker::Number.between(50, 105),
      exam_date: Faker::Date.backward(14)
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ExamsController. Be sure to keep this updated too.

  describe "GET #index" do
    it "assigns all exams as @exams" do
      exam = Exam.create! valid_attributes
      get :index, {}
      expect(assigns(:exams)).to eq([exam])
    end
  end

  describe "GET #show" do
    it "assigns the requested exam as @exam" do
      exam = Exam.create! valid_attributes
      get :show, {:id => exam.to_param}
      expect(assigns(:exam)).to eq(exam)
    end
  end

  describe "GET #new" do
    it "assigns a new exam as @exam" do
      get :new, {}
      expect(assigns(:exam)).to be_a_new(Exam)
    end
  end

  describe "GET #edit" do
    it "assigns the requested exam as @exam" do
      exam = Exam.create! valid_attributes
      get :edit, {:id => exam.to_param}
      expect(assigns(:exam)).to eq(exam)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Exam" do
        expect {
          request.env["HTTP_REFERER"] = exams_path
          post :create, {:exam => valid_attributes}
        }.to change(Exam, :count).by(1)
      end

      it "assigns a newly created exam as @exam" do
        request.env["HTTP_REFERER"] = exams_path
        post :create, {:exam => valid_attributes}
        expect(assigns(:exam)).to be_a(Exam)
        expect(assigns(:exam)).to be_persisted
      end

      it "redirects to the created exam" do
          request.env["HTTP_REFERER"] = exams_path
        post :create, {:exam => valid_attributes}
        expect(response).to redirect_to(exams_path)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved exam as @exam" do
        post :create, {:exam => invalid_attributes}
        expect(assigns(:exam)).to be_a_new(Exam)
      end

      it "re-renders the 'new' template" do
        post :create, {:exam => invalid_attributes}
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do


    context "with valid params" do
      let(:new_attributes) {
        {
          exam_date: Faker::Date.backward(14)
        }
      }

      it "updates the requested exam" do
        exam = Exam.create! valid_attributes
        request.env["HTTP_REFERER"] = exams_path
        put :update, {:id => exam.to_param, :exam => new_attributes}
        exam.reload
        expect(exam.exam_date).to eq(new_attributes[:exam_date])
      end

      it "assigns the requested exam as @exam" do
        exam = Exam.create! valid_attributes
        request.env["HTTP_REFERER"] = exams_path
        put :update, {:id => exam.to_param, :exam => valid_attributes}
        expect(assigns(:exam)).to eq(exam)
      end

      it "redirects to the exam" do
        exam = Exam.create! valid_attributes
        request.env["HTTP_REFERER"] = exams_path
        put :update, {:id => exam.to_param, :exam => valid_attributes}
        expect(response).to redirect_to(exams_path)
      end
    end

    context "with invalid params" do
      it "assigns the exam as @exam" do
        exam = Exam.create! valid_attributes
        request.env["HTTP_REFERER"] = exams_path
        put :update, {:id => exam.to_param, :exam => invalid_attributes}
        expect(assigns(:exam)).to eq(exam)
      end

      it "re-renders the 'edit' template" do
        exam = Exam.create! valid_attributes
        request.env["HTTP_REFERER"] = exams_path
        put :update, {:id => exam.to_param, :exam => invalid_attributes}
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested exam" do
      exam = Exam.create! valid_attributes
      expect {
        request.env["HTTP_REFERER"] = exams_path
        delete :destroy, {:id => exam.to_param}
      }.to change(Exam, :count).by(-1)
    end

    it "redirects to the exams list" do
      exam = Exam.create! valid_attributes
      request.env["HTTP_REFERER"] = exams_path
      delete :destroy, {:id => exam.to_param}
      expect(response).to redirect_to(exams_url)
    end
  end

end
