require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SchoolsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # School. As you add validations to School, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      name: Faker::University.name
    }
  }

  let(:invalid_attributes) {
    {
      name: nil
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SchoolsController. Be sure to keep this updated too.


  describe "GET #index" do
    login_coach
    it "assigns all schools as @schools" do
      school = School.create! valid_attributes
      get :index, {}
      expect(assigns(:schools)).to eq([school])
    end
  end

  describe "GET #show" do
    login_coach
    it "assigns the requested school as @school" do
      school = School.create! valid_attributes
      get :show, {:id => school.to_param}
      expect(assigns(:school)).to eq(school)
    end
  end

  describe "GET #new" do
    login_coach
    it "assigns a new school as @school" do
      get :new, {}
      expect(assigns(:school)).to be_a_new(School)
    end
  end

  describe "GET #edit" do
    login_coach
    it "assigns the requested school as @school" do
      school = School.create! valid_attributes
      get :edit, {:id => school.to_param}
      expect(assigns(:school)).to eq(school)
    end
  end

  describe "POST #create" do
    login_coach
    context "with valid params" do
      it "creates a new School" do
        expect {
          post :create, {:school => valid_attributes}
        }.to change(School, :count).by(1)
      end

      it "assigns a newly created school as @school" do
        post :create, {:school => valid_attributes}
        expect(assigns(:school)).to be_a(School)
        expect(assigns(:school)).to be_persisted
      end

      it "redirects to the created school" do
        post :create, {:school => valid_attributes}
        expect(response).to redirect_to(School.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved school as @school" do
        post :create, {:school => invalid_attributes}
        expect(assigns(:school)).to be_a_new(School)
      end

      it "re-renders the 'new' template" do
        post :create, {:school => invalid_attributes}
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    login_coach
    context "with valid params" do
      let(:new_attributes) {
        {
          name: Faker::University.name
        }
      }

      it "updates the requested school" do
        school = School.create! valid_attributes
        put :update, {:id => school.to_param, :school => new_attributes}
        school.reload
        expect(school.name).to eq(new_attributes[:name])
      end

      it "assigns the requested school as @school" do
        school = School.create! valid_attributes
        put :update, {:id => school.to_param, :school => valid_attributes}
        expect(assigns(:school)).to eq(school)
      end

      it "redirects to the school" do
        school = School.create! valid_attributes
        put :update, {:id => school.to_param, :school => valid_attributes}
        expect(response).to redirect_to(school)
      end
    end

    context "with invalid params" do
      it "assigns the school as @school" do
        school = School.create! valid_attributes
        put :update, {:id => school.to_param, :school => invalid_attributes}
        expect(assigns(:school)).to eq(school)
      end

      it "re-renders the 'edit' template" do
        school = School.create! valid_attributes
        put :update, {:id => school.to_param, :school => invalid_attributes}
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    login_coach
    it "destroys the requested school" do
      school = School.create! valid_attributes
      expect {
        delete :destroy, {:id => school.to_param}
      }.to change(School, :count).by(-1)
    end

    it "redirects to the schools list" do
      school = School.create! valid_attributes
      delete :destroy, {:id => school.to_param}
      expect(response).to redirect_to(schools_url)
    end
  end

end
